{% set name = "moyopy" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moyopy-{{ version }}.tar.gz
  sha256: 9c0783d88d33fbb8c5fbe568c2f71aa35a4fc8066ff984e2196f5b0e66632382

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0,<2.0  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - typing_extensions

test:
  imports:
    - moyopy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python binding of Moyo
  home: https://github.com/spglib/moyo
  license: Apache-2.0
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - ocefpaf
