schema_version: 1

context:
  version: "0.17.0"

package:
  name: moyopy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/moyopy/moyopy-${{ version }}.tar.gz
  sha256: 49b46dd2cba89d84d6ef9d8e3cb7cffa45e9898a57ef3d6b54d0dc820dff170e

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.0,<2.0
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python
    - typing_extensions

tests:
  - python:
      imports:
        - moyopy
      pip_check: true

about:
  summary: Python binding of Moyo
  license: MIT
  license_file: LICENSE-MIT
  homepage: https://github.com/spglib/moyo

extra:
  recipe-maintainers:
    - ocefpaf
